# Generated by Django 4.2.1 on 2026-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlumbingBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL: /demo/plumbing/{slug}', unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('review_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('years_in_business', models.PositiveIntegerField(default=1)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='plumbing/logos/')),
                ('tagline_en', models.CharField(blank=True, max_length=300)),
                ('tagline_es', models.CharField(blank=True, max_length=300)),
                ('description_en', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Полная ссылка из Google Maps → Share → Embed a map → src=...')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Plumbing Businesses',
                'ordering': ['name'],
            },
        ),
    ]
