# Generated by Django 4.2.1 on 2026-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumbingbusiness',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
