# Generated by Django 4.2.1 on 2026-03-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('trade', models.CharField(blank=True, max_length=60)),
                ('budget_range', models.CharField(blank=True, max_length=30)),
                ('timeline_pref', models.CharField(blank=True, max_length=30)),
                ('project_description', models.TextField()),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('ai_error', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
