# Generated by Django 4.2.1 on 2026-03-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webquoterequest',
            name='ip_address',
        ),
    ]
