# Generated by Django 4.2.1 on 2026-05-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
